spring.application.name=BT9_27-09-25
spring.datasource.url=jdbc:sqlserver://MINH-CHUONG:1433;databaseName=bt9_27-09-25;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=2357
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.properties.hibernate.format_sql=true

# Nếu cần chạy data.sql sau khi schema được tạo
spring.jpa.defer-datasource-initialization=true
spring.graphql.playground.enabled=true
spring.graphql.playground.mapping=/playground
spring.graphql.path=/graphql
server.port=8080
logging.level.org.springframework.graphql=INFO
logging.level.org.hibernate.SQL=DEBUG